import os

ORGANIZATION_NAME = os.getenv("AZURE_ORGANIZATION")
PROJECT_NAME = os.getenv("AZURE_PROJECT")
USER_EMAIL = os.getenv("AZURE_USER_EMAIL")
PERSONAL_ACCESS_TOKEN = os.getenv("AZURE_TOKEN")
TARGET_VELOCITY = int(os.getenv("TARGET_VELOCITY", "0"))
